services:
  server-agent:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: server-agent

    restart: unless-stopped

    environment:
      TZ: Europe/Moscow

    volumes:
      - /:/host

    privileged: true