
agent:
  uuid: "b86a756d-254d-47db-b48f-87c7e390d63d"
  name: "ServerAlexStack"
  version: "0.1.0"

panel:
  url: "ws://192.168.0.147/ws/agent"
  token: "d693935112653acf3d1bf0990d85625fb526c52a7e0570e4c3deb1e4186cffad"

heartbeat:
  interval: 15

terminal:
  shell: "/bin/bash"

monitor:
  interval: 2

logger:
  level: "info"